---

- name: Install
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config_internal.yaml
    - config.yaml
    - config_local.yaml

- import_playbook: pre_requisites.yaml

- import_playbook: pre_janus.yaml

- import_playbook: pre_nginx.yaml
  when: is_nginx_enabled == True

- import_playbook: pre_apuppet.yaml

- import_playbook: pre_certbot_first_cert.yaml
  when: is_certbot_enabled == True
