---

- name: Install
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config_internal.yaml
    - config.yaml
    - config_local.yaml

- name: Switch to install prerequisites
  import_playbook: pre_requisites.yaml
  when: ansible_distribution == 'Ubuntu'

- name: Switch to prepare Janus gateway
  import_playbook: pre_janus.yaml

- name: Switch to prepare Nginx webserver
  import_playbook: pre_nginx.yaml
  when: is_nginx_enabled == True

- name: Switch to prepare aPuppet
  import_playbook: pre_apuppet.yaml

- name: Switch to prepare Letsencrypt SSL certificate
  import_playbook: pre_certbot_first_cert.yaml
  when: is_certbot_enabled == True
