---

- name: Install prerequisites
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config.build.yaml
    - config.defaults.yaml
    - config.yaml

  tasks:
  - name: Ensure the aPuppet installing on Ubuntu >= 16.04
    fail:
      msg: aPuppet need Ubuntu version 16.04 and later
    when: not (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 16)

  - name: Install required system packages
    apt:
      package:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      update_cache: yes
      state: latest

  - name: Install python3 & setup accessories (for 20.04 and later)
    apt:
      package:
      - python3
      - python3-setuptools
      - python3-pip
    when: ansible_distribution_major_version|int >= 20

  - name: Install python2 & setup accessories (for 18.10 and earlier)
    apt:
      package:
      - python2
      - python-setuptools
      - python-pip
    when: ansible_distribution_major_version|int < 20

#  - name: Download pip for Python2
#    get_url:
#      url: https://bootstrap.pypa.io/get-pip.py
#      dest: /tmp/.get-pip.py
#      mode: 0644
#      force: yes
#
#  - name: Install pip for Python2
#    shell: python2 /tmp/.get-pip.py

  - name: Install required python packages
    pip:
      name:
        - PyYAML>=3.11
        - pyrsistent<0.17
        - docker>=4.3.0
        - docker-compose>=1.7.0

  - name: Add key for docker repository
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      update_cache: yes

  - name: Install Docker
    apt:
      package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present

  - name: Ensure Docker is started and enabled at boot
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure current user is added to the docker group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: docker
      append: true
    when: "ansible_user_id != 'root'"

  - name: Download docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
      dest: /usr/local/bin/docker-compose
      mode: 0755
      force: yes

  - name: Download docker-compose autocompletion (for bash only)
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/1.26.0/contrib/completion/bash/docker-compose
      dest: /etc/bash_completion.d/docker-compose
    when: "'/bash' in ansible_user_shell"

#  - name: Ensure aPuppet is not running
#    docker_compose:
#      project_src: ../
#      state: absent
#      stopped: yes
#      remove_volumes: yes
#      timeout: 30

#  - name: Start aPuppet
#    docker_compose:
#      project_src: ../
#      state: present
#      stopped: no