---

- name: Prepare Janus
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config.yaml
    - config_local.yaml

  tasks:
    - name: Build Janus Gateway image
      docker_image:
        name: janus-gateway:0.10.6
        source: build
        build:
          path: ./images/janus-gateway
          rm: yes
          pull: yes
