---

- name: Prepare Janus
  hosts: localhost
  connection: local
  vars_files:
    - config.build.yaml
    - config.defaults.yaml
    - ../config.yaml

  tasks:
    - name: Build Janus Gateway image. IT MAY TAKE A LONG TIME!
      docker_image:
        name: "{{ janus_image_name }}:{{ janus_image_tag }}"
        source: build
        build:
          path: ./images/janus-gateway
          rm: yes
          pull: yes
        force_source: yes
