---

- name: Install prerequisites
  hosts: localhost
  connection: local
  become: yes
  vars_files:
    - config.yaml
    - config_local.yaml

  tasks:

  - name: Update the APT package index, install packages
    apt:
      package:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      update_cache: yes
      state: latest

  - name: Add key for docker repository
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add docker repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
      state: present
      update_cache: yes

  - name: Install Docker
    apt:
      package:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: present

  - name: Ensure Docker is started and enabled at boot
    service:
      name: docker
      state: started
      enabled: true

  - name: Ensure current user is added to the docker group
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: docker
      append: true
    when: "ansible_user_id != 'root'"

  - name: Download docker-compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.26.0/docker-compose-{{ ansible_system }}-{{ ansible_machine }}
      dest: /usr/local/bin/docker-compose
      mode: 0755
      force: yes

  - name: Download docker-compose autocompletion (for bash only)
    get_url:
      url: https://raw.githubusercontent.com/docker/compose/1.26.0/contrib/completion/bash/docker-compose
      dest: /etc/bash_completion.d/docker-compose
    when: "'/bash' in ansible_user_shell"