---

- name: Switch to prepare aPuppet
  import_playbook: pre_apuppet.yaml

- name: Start aPuppet
  hosts: localhost
  connection: local
  vars_files:
    - config.build.yaml
    - config.defaults.yaml
    - ../config.yaml

  tasks:
    - name: (Re)Starting aPuppet
      docker_compose:
        project_src: ../
        state: present
        stopped: no
        restarted: yes
