---

- name: Switch to prepare aPuppet
  import_playbook: pre_apuppet.yaml

- name: Start aPuppet
  hosts: localhost
  connection: local
  vars_files:
    - config_internal.yaml
    - config.yaml
    - config_local.yaml

  tasks:
    - name: (Re)Start aPuppet
#      docker_compose:
#        project_src: ../
#        state: present
#        stopped: no
#        restarted: yes
    shell: docker-compose -f ./../docker-compose.yaml up --detach
