- name: Install python3 & setup accessories
  apt:
    package:
      - python3
      - python3-setuptools
      - python3-pip
  #when: ansible_distribution_major_version|int >= 20

- name: Get Python 3 path
  shell: "which python3"
  register: python3_abs_path

- debug: var=python3_abs_path

- name: Set Python 3 interpreter for deployment
  set_fact:
    ansible_python_interpreter: python3_abs_path.stdout
